site_name: Joy's Notebook
site_description: >-
  This is my coding notebook.
nav:
  - Home: index.md
  - R: r.md
  - Python: python.md
  - SQL: sql.md
  - About me: about.md
theme: 
  name: material
  custom_dir: material/overrides
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - content.code.annotate
  hide:
    - navigation
    - toc
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences