site_name: Joy's Notebook
site_description: >-
  This is my coding notebook.

# Page tree
nav:
  - Home: index.md
  - Python:
    - python/index.md
    - python/some_tips_python.md
    - Pandas and Numpy:
      - python/pandas_numpy/read_and_write_data.md
      - python/pandas_numpy/data_inspection.md
      - python/pandas_numpy/data_cleaning.md
      - python/pandas_numpy/data_selecting.md
      - python/pandas_numpy/table_reshaping.md
      - python/pandas_numpy/data_aggregation.md
      - python/pandas_numpy/string_manipulation.md
    - OOP:
      - python/oop/decorator.md
  - R:
    - R/index.md
    - R/some_tips.md
    - R/base_r.md
    - R/strings.md
    - Packages:
      - R/packages/dplyr.md
      - R/packages/purrr.md
      - R/packages/furrr.md
      - R/packages/rlang.md
    - Data Analysis:
      - R/data_analysis/r_data_analysis.md
    - Automation:
      - R/automation/r_automation.md
    - Officer:
      - R/officer/r_officer.md
    - Shiny:
      - R/shiny/r_shiny.md
  - SQL: sql.md
  - Git:
    - git.md
    - Git Basics:
      - git/git_basic/git_basic.md
    - Git Branching:
      - git/git_branching/git_branching.md
  - About me: about.md

# Configuration
theme: 
  name: material
  custom_dir: material/overrides
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.path
    - content.code.annotate
    - navigation.footer
  hide:
    - navigation
  favicon: assets/images/grey.png
  logo: assets/images/white_trans.png

# Extensions
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - toc:
      permalink: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # grid cards
  - attr_list
  - md_in_html
  # icon
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


extra:
  # footnote
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/joy-yue-ding/
    - icon: fontawesome/brands/github
      link: https://github.com/JoyDing0330
