site_name: Joy's Notebook
site_description: >-
  This is my coding notebook.

# Page tree
nav:
  - Home: index.md
  - R: r.md
  - Python:
    - Python/index.md
    - Pandas and Numpy:
      - Python/Pandas_numpy/read_write_data.md
      - Python/Pandas_numpy/data_inspection.md
      - Python/Pandas_numpy/data_cleaning.md
      - Python/Pandas_numpy/data_selecting.md
      - Python/Pandas_numpy/table_reshaping.md
      - Python/Pandas_numpy/data_aggregation.md
      - Python/Pandas_numpy/string_manipulation.md
    - OOP:
      - Python/OOP/decorator.md
  - SQL: sql.md
  - About me: about.md

# Configuration
theme: 
  name: material
  custom_dir: material/overrides
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.path
    - content.code.annotate
  hide:
    - navigation
  favicon: assets/images/favicon1.jpg

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - toc:
      permalink: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # grid cards
  - attr_list
  - md_in_html
  # icon
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
